# Use postgres/example user/password credentials
version: '3.8'

services:
  python-django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
# Automatically syncs the Docker filesystem with our local computer's filesystem
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#     - 8080:8080