# Use postgres/example user/password credentials
version: '3.8'

services:
  web:
    image: ghcr.io/megazorch/yacht-shop:release
    network_mode: host
    env_file:
      - ./.env
    volumes:
      - ./media:/yacht-shop/media