# Generated by Django 4.1.7 on 2023-03-26 14:17

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propulsion',
            name='engine_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Enter amount of hours engine has been in use.', null=True),
        ),
        migrations.AlterField(
            model_name='propulsion',
            name='engine_year',
            field=models.PositiveIntegerField(help_text='Enter the year of build of the engine.'),
        ),
        migrations.AlterField(
            model_name='propulsion',
            name='total_power',
            field=models.PositiveIntegerField(help_text='Enter the total power of engine in Horse Powers.'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='cabins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='double_berths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='heads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='single_berths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='hull_warranty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', help_text='Enter price of the yacht.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='year',
            field=models.PositiveIntegerField(help_text='Enter the year of build of the yacht.'),
        ),
    ]
