# Generated by Django 4.1.7 on 2023-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_propulsion_engine_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='length',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Enter the exact length of the yacht in ft.',
                max_digits=5),
        ),
    ]
