# Generated by Django 4.1.7 on 2023-03-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_yacht_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propulsion',
            name='engine_year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the year of build of the engine.', null=True),
        ),
        migrations.AlterField(
            model_name='propulsion',
            name='total_power',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the total power of engine in Horse Powers.', null=True),
        ),
    ]
