# Generated by Django 4.1.7 on 2023-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_yacht_yacht_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='model',
            field=models.CharField(
                help_text='Enter the model type of the yacht.',
                max_length=40),
        ),
    ]
