# Generated by Django 4.1.7 on 2023-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_specifications_dry_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter the name of category.', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='yacht',
            name='category',
            field=models.ManyToManyField(help_text='Enter the category of the yacht.', to='catalog.category'),
        ),
    ]
