# Generated by Django 4.1.7 on 2023-04-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_yacht_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('image',
                 models.ImageField(
                     upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='yacht_image',
        ),
        migrations.AddField(
            model_name='yacht',
            name='yacht_image',
            field=models.ManyToManyField(
                related_name='yachts',
                to='catalog.image'),
        ),
    ]
