# Generated by Django 4.1.7 on 2023-04-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_image_remove_yacht_yacht_image_yacht_yacht_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='yacht',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.yacht'),
        ),
    ]
