# Generated by Django 4.1.7 on 2023-04-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_image_yacht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='yacht_image',
            field=models.ManyToManyField(null=True, related_name='yachts', to='catalog.image'),
        ),
    ]
