# Generated by Django 4.1.7 on 2023-04-15 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_yacht_yacht_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='yacht',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.yacht'),
        ),
    ]
