# Generated by Django 4.1.7 on 2023-04-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_image_yacht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='yacht',
        ),
    ]
