# Generated by Django 4.2 on 2023-04-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_image_yacht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['broker']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image']},
        ),
        migrations.CreateModel(
            name='CartLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Enter number of items.')),
                ('cart', models.ForeignKey(help_text='Choose Cart id.', on_delete=django.db.models.deletion.CASCADE, to='catalog.cart')),
                ('yacht', models.ForeignKey(help_text='Choose Yacht id.', on_delete=django.db.models.deletion.CASCADE, to='catalog.yacht')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
