# Generated by Django 4.2 on 2023-04-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_cart_alter_broker_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='yacht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.yacht'),
        ),
    ]
