# Generated by Django 4.2 on 2023-04-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_image_yacht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yacht',
            name='yacht_image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
