# Generated by Django 4.2 on 2023-04-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_yacht_yacht_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlineitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartlineitem',
            name='yacht',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartLineItem',
        ),
    ]
