# Generated by Django 4.2 on 2023-04-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
