# Generated by Django 4.2 on 2023-04-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['image'],
            },
        ),
        migrations.CreateModel(
            name='CartLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Enter number of items.')),
                ('cart', models.ForeignKey(help_text='Choose Cart id.', on_delete=django.db.models.deletion.CASCADE, to='catalog.cart')),
                ('yacht', models.ForeignKey(help_text='Choose Yacht id.', on_delete=django.db.models.deletion.CASCADE, to='catalog.yacht')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='yacht',
            name='yacht_image',
            field=models.ManyToManyField(related_name='yachts', to='catalog.image'),
        ),
    ]
