# Generated by Django 4.2 on 2023-04-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='cartlineitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
