# Generated by Django 4.2.1 on 2023-05-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0026_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlineitem',
            name='highlighted',
            field=models.TextField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='cartlineitem',
            name='owner',
            field=models.ForeignKey(
                default='1',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carts',
                to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
