# Generated by Django 4.2.1 on 2023-05-07 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0027_cartlineitem_highlighted_cartlineitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlineitem',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
