name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - run: pipenv install

      - name: Run pylint-django
        run: pipenv run pylint --ignore=catalog/migrations --load-plugins pylint_django
          --django-settings-module=yacht_shop.settings catalog
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_HOST: localhost
          DB_NAME: postgres
          DB_PASS: postgres
          DB_PORT: 5432
          DB_USER: postgres
